name: CI Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y gcc-arm-none-eabi make

      - name: Build Firmware
        run: make

      - name: Upload Firmware Artifact
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: build/firmware.elf
